<?php

class OperacionReal extends Operacion
{
        public function __construct($cadena)
        {
            parent::__construct($cadena);
        }
        public function calcula()
        {
            $resultado=null;
            // TODO: Implement calcula() method.
            switch ($this->operador){
                case '+':
                    $resultado = $this->op1 + $this->op2;
                    break;
                case '-':
                    $resultado = $this->op1 - $this->op2;
                    break;
                case '*':
                    $resultado = $this->op1 * $this->op2;
                    break;
                case '/':
                    $resultado = $this->op1 / $this->op2;
                    break;
            }
            return $resultado;
        }
        public function __tostring()
        {

            return parent::__tostring(); // TODO: Change the autogenerated stub


        }


}